FizzBuzzWeb/Models/FizzBuzzModel.cs
namespace FizzBuzzWeb.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using PagedList;
 

    public class FizzBuzzModel
    {
        public IPagedList<string> FizzBuzzNumbers { get; set; }

        [RegularExpression(@"^\d+$")]
        [Required(ErrorMessage = "This filed is required")]
        [Range(1, 100, ErrorMessage = "Please enter the value between 1 to 1000")]
        [DisplayName("Enter Integer Number")]
        public int Input { get; set; }
    }
}

FizzBuzzWeb/Controllers/FizzBuzzController.cs
namespace FizzBuzzWeb.Controllers
{
    using FizzBuzzWeb.Models;
    using System.Web.Mvc;
    using PagedList;
    using FizzBuzz.Services.Interface;

    public class FizzBuzzController : Controller
    {
        private int pageSize = 20;
        private IFizzBuzzService fizzBuzz;

        public FizzBuzzController(IFizzBuzzService fizzBuzz)
        {
            this.fizzBuzz = fizzBuzz;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return this.View(new FizzBuzzModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(FizzBuzzModel model)
        {
            model.FizzBuzzNumbers = this.fizzBuzz.GetFizzBuzzResult(model.Input).ToPagedList(1, pageSize);
            return View("Index", model);

        }

        public ActionResult Navigate(FizzBuzzModel model, int page)
        {
            model.FizzBuzzNumbers = this.fizzBuzz.GetFizzBuzzResult(model.Input).ToPagedList(page, pageSize);
            return View("Index", model); ;
        }
    }
}

FizzBuzzWeb/Views/FizzBuzz/Index.cshtml
@using PagedList.Mvc
@model FizzBuzzWeb.Models.FizzBuzzModel

@using (Html.BeginForm("Index", "FizzBuzz", FormMethod.Post))
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(m => m.Input)
        @Html.TextBoxFor(m => m.Input, new { placeholder = "Enter Integer Number", Value = "" })
        @Html.ValidationMessageFor(m => m.Input)

    </div>
    <div class="form-group">
        <input type="submit" value="SUBMIT" class="btn-default" />
    </div>

     <div>
    @if (Model.FizzBuzzNumbers != null)
    {
        foreach (var val in Model.FizzBuzzNumbers)
        {
            <div>@val</div>

        }
        <div class="PageColor">
            Page @(Model.FizzBuzzNumbers.PageCount < Model.FizzBuzzNumbers.PageNumber ? 0 : Model.FizzBuzzNumbers.PageNumber) of @Model.FizzBuzzNumbers.PageCount
            @Html.PagedListPager(Model.FizzBuzzNumbers, page => Url.Action("Navigate", "FizzBuzz", new { Model.Input, page }));
        </div>
    }
     </div>
}